import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { existsSync } from "fs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

// Detect entry point: prefer src/main.ts, fallback to main.ts
const hasSrcMain = existsSync("src/main.ts");
const hasRootMain = existsSync("main.ts");

if (hasSrcMain && hasRootMain) {
  console.warn("WARNING: Both src/main.ts and main.ts exist. Using src/main.ts as entry point.");
  console.warn("Consider removing one to avoid confusion.");
}
if (!hasSrcMain && !hasRootMain) {
  console.error("ERROR: Neither src/main.ts nor main.ts found!");
  process.exit(1);
}

// Set entry point based on what exists
const entryPoint = hasSrcMain ? "src/main.ts" : "main.ts";

// Always build to root for simplicity
const outfile = "main.js";

// Production builds must be reproducible. An inline sourcemap embeds the
// build machine's absolute file paths into main.js, so CI and the Obsidian
// scorecard's reproducer produce byte-different output and the "build
// verification" check fails. Ship production with no sourcemap; keep the
// inline sourcemap only for the dev/watch build for local debugging.
const isProduction =
	process.argv.slice(2).includes("build") ||
	process.argv.slice(2).includes("production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: [entryPoint],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: isProduction ? false : "inline",
	treeShaking: true,
	outfile: outfile,
	minify: false,
});

// Check if this is a one-time build or watch mode
// Check for "build" or "production" argument - supports both patterns
const args = process.argv.slice(2);
const isOneTimeBuild = args.includes("build") || args.includes("production");

if (isOneTimeBuild) {
	// Production build: build once and exit
	await context.rebuild();
	console.log("\n✓ Build complete!");
	console.log("📦 Release files:");
	console.log("   - main.js");
	if (existsSync("manifest.json")) {
		console.log("   - manifest.json");
	}
	if (existsSync("styles.css")) {
		console.log("   - styles.css");
	}
	console.log("\n💡 Upload these files to GitHub releases\n");
	await context.dispose();
	process.exit(0);
} else {
	// Development mode: watch for changes
	console.log("\n✓ Development build running in watch mode");
	console.log("📝 Building to main.js in root");
	console.log("💡 For production builds, run: pnpm build\n");
	await context.watch();
}
